name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: search0607
  AZURE_ACR_NAME: container0603
  AZURE_RESOURCE_GROUP_NAME: group-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ env.AZURE_ACR_NAME }}.azurecr.io/household:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
      env:
        AZURE_ACR_NAME: ${{ env.AZURE_ACR_NAME }}

    - name: Deploy to Web App
      run: |
        IMAGE_NAME=${{ env.AZURE_ACR_NAME }}.azurecr.io/household:latest
        az webapp config container set \
          --name $AZURE_WEBAPP_NAME \
          --resource-group $AZURE_RESOURCE_GROUP_NAME \
          --docker-custom-image-name $IMAGE_NAME \
          --docker-registry-server-url https://${{ env.AZURE_ACR_NAME }}.azurecr.io
